// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cipnknfyujbjhkyflbdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcG5rbmZ5dWpiamhreWZsYmRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjcwMDgsImV4cCI6MjA2MDY0MzAwOH0.p1r68AYLylfColxDJwFXl1U2g8OAdQrG6B4KzCDv6Ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);